title: shazld poetry & inspirations
author: shazld  
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Poetry and inspirations by shazld.

# social links
twitter_username: shazld # DO NOT include the @ character, or else the build will fail!
github_username:  shazlds # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
